import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TextInput, TouchableOpacity, Image, ActivityIndicator, ScrollView, Linking, Modal } from 'react-native';
import { showNeonAlert } from '../../components/NeonAlert';
import { useApp } from '../../context/AppContext';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system';
import { Audio } from 'expo-av';
import { Asset } from 'expo-asset';
import SetSecurityPinModal from '../../components/SetSecurityPinModal';
import { hasSecurityPin, isBiometricAvailable } from '../../utils/applock';
import Constants from 'expo-constants';

const APP_VERSION = Constants.expoConfig?.version || '1.0.0';

// NOVA's bundled tones (generated by scripts/gen-tones.js). Any of these can be
// applied to the Call / Message / Group slot. Short ones suit notifications,
// the longer "beacon"/"aurora" suit call ringtones.
const BUILTIN_TONES: { id: string; name: string; kind: 'short' | 'ring'; module: any; ext?: 'wav' | 'mp3' }[] = [
  { id: 'pulse', name: 'Pulse', kind: 'short', module: require('../../../assets/tones/pulse.wav') },
  { id: 'chime', name: 'Chime', kind: 'short', module: require('../../../assets/tones/chime.wav') },
  { id: 'ripple', name: 'Ripple', kind: 'short', module: require('../../../assets/tones/ripple.wav') },
  { id: 'glow', name: 'Glow', kind: 'short', module: require('../../../assets/tones/glow.wav') },
  { id: 'beacon', name: 'Beacon (ring)', kind: 'ring', module: require('../../../assets/tones/beacon.wav') },
  { id: 'aurora', name: 'Aurora (ring)', kind: 'ring', module: require('../../../assets/tones/aurora.wav') },
  { id: 'marimba', name: 'Marimba (ring)', kind: 'ring', module: require('../../../assets/tones/marimba.wav') },
  { id: 'classic', name: 'Classic Ring', kind: 'ring', module: require('../../../assets/tones/classic.wav') },
  { id: 'bright', name: 'Bright', kind: 'short', module: require('../../../assets/tones/bright.wav') },
  { id: 'bubble', name: 'Bubble', kind: 'short', module: require('../../../assets/tones/bubble.wav') },
  // User-supplied music ringtones (mp3).
  { id: 'cool', name: 'Cool (ring)', kind: 'ring', ext: 'mp3', module: require('../../../assets/tones/cool.mp3') },
  { id: 'melody', name: 'Melody (ring)', kind: 'ring', ext: 'mp3', module: require('../../../assets/tones/melody.mp3') },
  { id: 'romantic', name: 'Romantic (ring)', kind: 'ring', ext: 'mp3', module: require('../../../assets/tones/romantic.mp3') },
];

export default function SettingsScreen() {
  const { user, updateProfile, logout, chatWallpaper, setChatWallpaper, selectedRingtone, setSelectedRingtone, customTones, setCustomTone, privacyLastSeen, setPrivacyLastSeen, privacyReadReceipts, setPrivacyReadReceipts, appLockEnabled, toggleAppLock } = useApp();
  const [displayName, setDisplayName] = useState(user?.displayName || '');
  const [about, setAbout] = useState(user?.about || '');
  const [avatarUrl, setAvatarUrl] = useState(user?.avatarUrl || '');
  const [updating, setUpdating] = useState(false);
  const [showPinSetup, setShowPinSetup] = useState(false);
  const [bioAvailable, setBioAvailable] = useState(false);

  useEffect(() => { isBiometricAvailable().then(setBioAvailable); }, []);

  const handleToggleAppLock = async (value: boolean) => {
    if (value) {
      const has = await hasSecurityPin();
      if (has) {
        await toggleAppLock(true);
        showNeonAlert({ title: 'APP LOCK ON', message: 'NOVA will ask for fingerprint / PIN when you open it.', icon: 'lock-closed', iconColor: '#10b981', borderColor: '#10b981' });
      } else {
        setShowPinSetup(true); // need to create a PIN first
      }
    } else {
      await toggleAppLock(false);
    }
  };

  const onPinSetupDone = async (success: boolean) => {
    setShowPinSetup(false);
    if (success) {
      await toggleAppLock(true);
      showNeonAlert({ title: 'APP LOCK ON', message: 'PIN set. NOVA is now protected with App Lock.', icon: 'shield-checkmark', iconColor: '#10b981', borderColor: '#10b981' });
    }
  };

  const getInitials = (name: string) => {
    return name ? name.charAt(0).toUpperCase() : '?';
  };

  const handlePickImage = async () => {
    showNeonAlert({
      title: 'PROFILE PICTURE',
      message: 'Choose a source for your avatar:',
      buttons: [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Camera', onPress: handleLaunchCamera },
        { text: 'Gallery', onPress: handleLaunchGallery }
      ],
      icon: 'camera-outline',
      iconColor: '#0df',
      borderColor: '#0df',
    });
  };

  const handleLaunchCamera = async () => {
    const { status } = await ImagePicker.requestCameraPermissionsAsync();
    if (status !== 'granted') {
      showNeonAlert({
        title: 'PERMISSION DENIED',
        message: 'Camera access permission is required to take photos!',
        icon: 'alert-circle-outline',
        iconColor: '#f59e0b',
        borderColor: '#f59e0b',
      });
      return;
    }

    const result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [1, 1],
      quality: 0.3,
      base64: true,
    });

    if (!result.canceled && result.assets[0].base64) {
      const base64Uri = `data:image/jpeg;base64,${result.assets[0].base64}`;
      setAvatarUrl(base64Uri);
    }
  };

  const handleLaunchGallery = async () => {
    const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (status !== 'granted') {
      showNeonAlert({
        title: 'PERMISSION DENIED',
        message: 'Gallery access permission is required to select photos!',
        icon: 'alert-circle-outline',
        iconColor: '#f59e0b',
        borderColor: '#f59e0b',
      });
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [1, 1],
      quality: 0.3,
      base64: true,
    });

    if (!result.canceled && result.assets[0].base64) {
      const base64Uri = `data:image/jpeg;base64,${result.assets[0].base64}`;
      setAvatarUrl(base64Uri);
    }
  };

  const handlePickWallpaper = async () => {
    const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (status !== 'granted') {
      showNeonAlert({
        title: 'PERMISSION DENIED',
        message: 'Gallery access permission is required to select wallpapers!',
        icon: 'alert-circle-outline',
        iconColor: '#f59e0b',
        borderColor: '#f59e0b',
      });
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      quality: 0.5,
      base64: true,
    });

    if (!result.canceled && result.assets[0].base64) {
      const base64Uri = `data:image/jpeg;base64,${result.assets[0].base64}`;
      await setChatWallpaper(base64Uri);
      showNeonAlert({
        title: 'WALLPAPER CHANGED',
        message: 'Custom chat background wallpaper set successfully!',
        icon: 'checkmark-circle-outline',
        iconColor: '#10b981',
        borderColor: '#10b981',
      });
    }
  };

  const handleSaveProfile = async () => {
    if (!displayName.trim()) {
      showNeonAlert({
        title: 'VALIDATION ERROR',
        message: 'Display Name cannot be empty',
        icon: 'close-circle-outline',
        iconColor: '#f43f5e',
        borderColor: '#f43f5e',
      });
      return;
    }

    setUpdating(true);
    const success = await updateProfile(displayName.trim(), about.trim(), avatarUrl);
    setUpdating(false);

    if (success) {
      showNeonAlert({
        title: 'SUCCESS',
        message: 'Profile details updated successfully!',
        buttons: [{ text: 'OK' }],
        icon: 'checkmark-circle-outline',
        iconColor: '#10b981',
        borderColor: '#10b981',
      });
    }
  };

  const handleLogout = () => {
    showNeonAlert({
      title: 'LOG OUT',
      message: 'Are you sure you want to log out of Nova?',
      buttons: [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Log Out', style: 'destructive', onPress: logout }
      ],
      icon: 'log-out-outline',
      iconColor: '#f43f5e',
      borderColor: '#f43f5e',
    });
  };

  const SUPPORT_EMAIL = 'nova.verifying@gmail.com';

  // ── Custom tone selection (call ringtone / message tone / group tone) ──
  const [previewSound, setPreviewSound] = useState<Audio.Sound | null>(null);
  const [previewingUri, setPreviewingUri] = useState<string | null>(null);
  const [busyTone, setBusyTone] = useState<string | null>(null);
  // Built-in tone picker modal: which slot we're choosing for, and which preset is previewing.
  const [presetKind, setPresetKind] = useState<'call' | 'message' | 'group' | null>(null);
  const [previewingPresetId, setPreviewingPresetId] = useState<string | null>(null);

  // Stop & release any preview sound when leaving the screen.
  useEffect(() => {
    return () => {
      if (previewSound) {
        previewSound.stopAsync().catch(() => {});
        previewSound.unloadAsync().catch(() => {});
      }
    };
  }, [previewSound]);

  const TONES_DIR = FileSystem.documentDirectory + 'tones/';

  const ensureTonesDir = async () => {
    const info = await FileSystem.getInfoAsync(TONES_DIR);
    if (!info.exists) {
      await FileSystem.makeDirectoryAsync(TONES_DIR, { intermediates: true });
    }
  };

  const toneLabels: Record<'call' | 'message' | 'group', string> = {
    call: 'Call Ringtone',
    message: 'Message Tone',
    group: 'Group Message Tone',
  };

  const handlePickTone = async (kind: 'call' | 'message' | 'group') => {
    try {
      const res = await DocumentPicker.getDocumentAsync({ type: 'audio/*', copyToCacheDirectory: true, multiple: false });
      if (res.canceled || !res.assets || !res.assets[0]) return;
      const asset = res.assets[0];
      setBusyTone(kind);
      await ensureTonesDir();
      // Copy into the app's persistent storage so the URI survives app restarts.
      const safeName = (asset.name || 'tone.mp3').replace(/[^a-zA-Z0-9._-]/g, '_');
      const dest = `${TONES_DIR}${kind}_${Date.now()}_${safeName}`;
      await FileSystem.copyAsync({ from: asset.uri, to: dest });
      await setCustomTone(kind, { uri: dest, name: asset.name || safeName });
      showNeonAlert({
        title: 'TONE SET',
        message: `${toneLabels[kind]} set to "${asset.name || safeName}".`,
        icon: 'musical-notes-outline', iconColor: '#10b981', borderColor: '#10b981',
      });
    } catch (e: any) {
      console.error('Tone pick error:', e);
      showNeonAlert({ title: 'COULD NOT SET TONE', message: 'Failed to set this audio file. Please try another.', icon: 'alert-circle-outline', iconColor: '#f43f5e', borderColor: '#f43f5e' });
    } finally {
      setBusyTone(null);
    }
  };

  const stopPreview = async () => {
    if (previewSound) {
      try { await previewSound.stopAsync(); } catch (e) {}
      try { await previewSound.unloadAsync(); } catch (e) {}
    }
    setPreviewSound(null);
    setPreviewingUri(null);
    setPreviewingPresetId(null);
  };

  // Toggle preview: tapping the same tone again stops it (one play/stop button).
  const handlePreviewTone = async (uri: string) => {
    if (previewingUri === uri) {
      await stopPreview();
      return;
    }
    await stopPreview();
    try {
      const { sound } = await Audio.Sound.createAsync({ uri }, { shouldPlay: true, volume: 1.0 });
      setPreviewSound(sound);
      setPreviewingUri(uri);
      sound.setOnPlaybackStatusUpdate((status: any) => {
        if (status.didJustFinish) {
          sound.unloadAsync().catch(() => {});
          setPreviewSound(null);
          setPreviewingUri(null);
        }
      });
    } catch (e) {
      setPreviewingUri(null);
      showNeonAlert({ title: 'PREVIEW FAILED', message: 'Could not play this tone.', icon: 'alert-circle-outline', iconColor: '#f59e0b', borderColor: '#f59e0b' });
    }
  };

  const handleClearTone = async (kind: 'call' | 'message' | 'group') => {
    const tone = customTones[kind];
    if (tone && previewingUri === tone.uri) await stopPreview();
    await setCustomTone(kind, null);
  };

  // ── Built-in tones ──

  // Preview a bundled tone (require() module) with a play/stop toggle.
  const handlePreviewBuiltIn = async (preset: typeof BUILTIN_TONES[number]) => {
    if (previewingPresetId === preset.id) {
      await stopPreview();
      return;
    }
    await stopPreview();
    try {
      const { sound } = await Audio.Sound.createAsync(preset.module, { shouldPlay: true, volume: 1.0 });
      setPreviewSound(sound);
      setPreviewingPresetId(preset.id);
      sound.setOnPlaybackStatusUpdate((status: any) => {
        if (status.didJustFinish) {
          sound.unloadAsync().catch(() => {});
          setPreviewSound(null);
          setPreviewingPresetId(null);
        }
      });
    } catch (e) {
      setPreviewingPresetId(null);
      showNeonAlert({ title: 'PREVIEW FAILED', message: 'Could not play this tone.', icon: 'alert-circle-outline', iconColor: '#f59e0b', borderColor: '#f59e0b' });
    }
  };

  // Apply a bundled tone to a slot: copy the asset into persistent storage so the
  // existing { uri }-based playback path (call ringtone / message tone) just works.
  const applyBuiltInTone = async (kind: 'call' | 'message' | 'group', preset: typeof BUILTIN_TONES[number]) => {
    try {
      setBusyTone(kind);
      await stopPreview();
      await ensureTonesDir();
      const asset = Asset.fromModule(preset.module);
      await asset.downloadAsync();
      const src = asset.localUri || asset.uri;
      const dest = `${TONES_DIR}${kind}_builtin_${preset.id}.${preset.ext || 'wav'}`;
      try { await FileSystem.deleteAsync(dest, { idempotent: true }); } catch (e) {}
      await FileSystem.copyAsync({ from: src, to: dest });
      await setCustomTone(kind, { uri: dest, name: preset.name });
      setPresetKind(null);
      showNeonAlert({
        title: 'TONE SET',
        message: `${toneLabels[kind]} set to "${preset.name}".`,
        icon: 'musical-notes-outline', iconColor: '#10b981', borderColor: '#10b981',
      });
    } catch (e: any) {
      console.error('Built-in tone error:', e);
      showNeonAlert({ title: 'COULD NOT SET TONE', message: 'Failed to apply this built-in tone.', icon: 'alert-circle-outline', iconColor: '#f43f5e', borderColor: '#f43f5e' });
    } finally {
      setBusyTone(null);
    }
  };

  const handleContactSupport = async () => {
    const url = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent('NOVA Support Request')}`;
    try {
      const ok = await Linking.canOpenURL(url);
      if (ok) {
        await Linking.openURL(url);
      } else {
        showNeonAlert({
          title: 'CONTACT SUPPORT',
          message: `Reach us at ${SUPPORT_EMAIL}`,
          icon: 'mail-outline',
          iconColor: '#0df',
          borderColor: '#0df',
        });
      }
    } catch {
      showNeonAlert({
        title: 'CONTACT SUPPORT',
        message: `Reach us at ${SUPPORT_EMAIL}`,
        icon: 'mail-outline',
        iconColor: '#0df',
        borderColor: '#0df',
      });
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
      {/* Profile Picture Header Section */}
      <View style={styles.avatarSection}>
        <TouchableOpacity style={styles.avatarWrapper} onPress={handlePickImage}>
          {avatarUrl ? (
            <Image source={{ uri: avatarUrl }} style={styles.avatar} />
          ) : (
            <View style={[styles.avatarFallback, { backgroundColor: '#0df' }]}>
              <Text style={styles.avatarFallbackText}>{getInitials(displayName || 'U')}</Text>
            </View>
          )}
          <View style={styles.cameraIconBg}>
            <Ionicons name="camera" size={18} color="#090d16" />
          </View>
        </TouchableOpacity>
        <Text style={styles.usernameText}>@{user?.username}</Text>
        <Text style={styles.profileTip}>Tap avatar circle to change picture</Text>
      </View>

      {/* Profile Fields Section */}
      <View style={styles.formContainer}>
        {/* Display Name Input */}
        <View style={styles.inputContainer}>
          <Text style={styles.label}>Display Name</Text>
          <View style={styles.inputWrapper}>
            <Ionicons name="person-outline" size={20} color="#64748b" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="Display Name"
              placeholderTextColor="#475569"
              value={displayName}
              onChangeText={setDisplayName}
              autoCorrect={false}
            />
          </View>
        </View>

        {/* About Status Input */}
        <View style={styles.inputContainer}>
          <Text style={styles.label}>About Status</Text>
          <View style={styles.inputWrapper}>
            <Ionicons name="sparkles-outline" size={20} color="#64748b" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="About Status"
              placeholderTextColor="#475569"
              value={about}
              onChangeText={setAbout}
            />
          </View>
        </View>

        {/* Save Button */}
        <TouchableOpacity style={styles.saveButton} onPress={handleSaveProfile} disabled={updating}>
          {updating ? (
            <ActivityIndicator color="#090d16" />
          ) : (
            <>
              <Ionicons name="checkmark-sharp" size={18} color="#090d16" style={{ marginRight: 6 }} />
              <Text style={styles.saveButtonText}>Save Details</Text>
            </>
          )}
        </TouchableOpacity>

        {/* Matrix Personalisation Section */}
        <View style={styles.personalizationSection}>
          <Text style={styles.sectionHeaderTitle}>Matrix Personalisation</Text>

          {/* Chat Background Wallpaper */}
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingTitle}>Chat Wallpaper</Text>
              <Text style={styles.settingSubtitle}>
                {chatWallpaper ? 'Custom matrix wallpaper active' : 'Default deep space canvas active'}
              </Text>
            </View>
            <View style={styles.wallpaperButtons}>
              <TouchableOpacity style={styles.miniBtn} onPress={handlePickWallpaper}>
                <Ionicons name="image-outline" size={16} color="#0df" />
                <Text style={styles.miniBtnText}>Select</Text>
              </TouchableOpacity>
              {chatWallpaper && (
                <TouchableOpacity style={[styles.miniBtn, { borderColor: '#ef4444', marginLeft: 8 }]} onPress={() => setChatWallpaper(null)}>
                  <Ionicons name="trash-outline" size={16} color="#ef4444" />
                </TouchableOpacity>
              )}
            </View>
          </View>

          {/* Custom Tones — pick any audio from device */}
          <View style={styles.settingRowCol}>
            <Text style={styles.settingTitleCol}>Notification & Call Tones</Text>
            {(['call', 'message', 'group'] as const).map((kind) => {
              const tone = customTones[kind];
              return (
                <View key={kind} style={styles.toneRow}>
                  <View style={styles.toneIconWrap}>
                    <Ionicons
                      name={kind === 'call' ? 'call-outline' : kind === 'group' ? 'people-outline' : 'chatbubble-outline'}
                      size={18}
                      color="#0df"
                    />
                  </View>
                  <View style={styles.toneInfo}>
                    <Text style={styles.toneTitle}>{toneLabels[kind]}</Text>
                    <Text style={styles.toneSub} numberOfLines={1}>{tone ? tone.name : 'Default'}</Text>
                  </View>
                  {tone && (
                    <TouchableOpacity style={styles.toneIconBtn} onPress={() => handlePreviewTone(tone.uri)}>
                      <Ionicons name={previewingUri === tone.uri ? 'stop' : 'play'} size={15} color={previewingUri === tone.uri ? '#f43f5e' : '#10b981'} />
                    </TouchableOpacity>
                  )}
                  <TouchableOpacity style={styles.toneIconBtn} onPress={() => { stopPreview(); setPresetKind(kind); }}>
                    <Ionicons name="musical-notes-outline" size={15} color="#a78bfa" />
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.toneIconBtn} onPress={() => handlePickTone(kind)} disabled={busyTone === kind}>
                    {busyTone === kind
                      ? <ActivityIndicator size="small" color="#0df" />
                      : <Ionicons name="folder-open-outline" size={15} color="#0df" />}
                  </TouchableOpacity>
                  {tone && (
                    <TouchableOpacity style={styles.toneIconBtn} onPress={() => handleClearTone(kind)}>
                      <Ionicons name="close" size={15} color="#ef4444" />
                    </TouchableOpacity>
                  )}
                </View>
              );
            })}
            <Text style={styles.toneHint}>Tap the musical-note icon for NOVA's built-in tones, or the folder icon to pick any audio from your device. Leave as Default to use the standard tone.</Text>
          </View>

          {/* Privacy Toggles */}
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingTitle}>Broadcast Online Status</Text>
              <Text style={styles.settingSubtitle}>Show online presence & last seen</Text>
            </View>
            <TouchableOpacity
              style={[styles.toggleSwitch, privacyLastSeen && styles.toggleSwitchActive]}
              onPress={() => setPrivacyLastSeen(!privacyLastSeen)}
            >
              <View style={[styles.toggleCircle, privacyLastSeen && styles.toggleCircleActive]} />
            </TouchableOpacity>
          </View>

          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingTitle}>Read Receipts (Blue Ticks)</Text>
              <Text style={styles.settingSubtitle}>Grey receipts show if deactivated</Text>
            </View>
            <TouchableOpacity
              style={[styles.toggleSwitch, privacyReadReceipts && styles.toggleSwitchActive]}
              onPress={() => setPrivacyReadReceipts(!privacyReadReceipts)}
            >
              <View style={[styles.toggleCircle, privacyReadReceipts && styles.toggleCircleActive]} />
            </TouchableOpacity>
          </View>
        </View>

        {/* App Security Section */}
        <View style={styles.helpSection}>
          <Text style={styles.sectionHeaderTitle}>App Security</Text>
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingTitle}>App Lock</Text>
              <Text style={styles.settingSubtitle}>
                {bioAvailable ? 'Require fingerprint / PIN to open NOVA' : 'Require a PIN to open NOVA'}
              </Text>
            </View>
            <TouchableOpacity
              style={[styles.toggleSwitch, appLockEnabled && styles.toggleSwitchActive]}
              onPress={() => handleToggleAppLock(!appLockEnabled)}
            >
              <View style={[styles.toggleCircle, appLockEnabled && styles.toggleCircleActive]} />
            </TouchableOpacity>
          </View>
          <Text style={styles.toneHint}>
            Tip: long-press any chat to lock it. Locked chats are hidden and open only with your fingerprint / PIN.
          </Text>
        </View>

        {/* Help & Support Section */}
        <View style={styles.helpSection}>
          <Text style={styles.sectionHeaderTitle}>Help & Support</Text>

          <TouchableOpacity style={styles.helpRow} onPress={handleContactSupport} activeOpacity={0.7}>
            <View style={styles.helpIconBg}>
              <Ionicons name="mail-outline" size={18} color="#0df" />
            </View>
            <View style={styles.helpInfo}>
              <Text style={styles.helpTitle}>Contact Support</Text>
              <Text style={styles.helpSubtitle}>{SUPPORT_EMAIL}</Text>
            </View>
            <Ionicons name="open-outline" size={18} color="#475569" />
          </TouchableOpacity>

          <View style={styles.helpRow}>
            <View style={styles.helpIconBg}>
              <Ionicons name="information-circle-outline" size={18} color="#0df" />
            </View>
            <View style={styles.helpInfo}>
              <Text style={styles.helpTitle}>App Version</Text>
              <Text style={styles.helpSubtitle}>NOVA v{APP_VERSION}</Text>
            </View>
          </View>
        </View>

        {/* Log Out Button */}
        <TouchableOpacity style={styles.logoutButton} onPress={handleLogout}>
          <Ionicons name="log-out-outline" size={20} color="#ef4444" style={{ marginRight: 8 }} />
          <Text style={styles.logoutButtonText}>Log Out Account</Text>
        </TouchableOpacity>

        {/* Created by footer */}
        <Text style={styles.creditText}>Created by Ansh Verma</Text>
      </View>

      <SetSecurityPinModal visible={showPinSetup} onDone={onPinSetupDone} />

      {/* Built-in tone picker */}
      <Modal visible={!!presetKind} transparent animationType="fade" onRequestClose={() => { stopPreview(); setPresetKind(null); }}>
        <View style={styles.presetOverlay}>
          <View style={styles.presetCard}>
            <View style={styles.presetHeader}>
              <Text style={styles.presetTitle}>{presetKind ? `Built-in ${toneLabels[presetKind]}` : 'Built-in Tones'}</Text>
              <TouchableOpacity onPress={() => { stopPreview(); setPresetKind(null); }}>
                <Ionicons name="close" size={22} color="#cbd5e1" />
              </TouchableOpacity>
            </View>
            <Text style={styles.presetSub}>Tap play to preview, then "Set" to apply.</Text>
            {BUILTIN_TONES.map((preset) => (
              <View key={preset.id} style={styles.presetRow}>
                <TouchableOpacity style={styles.presetPlayBtn} onPress={() => handlePreviewBuiltIn(preset)}>
                  <Ionicons name={previewingPresetId === preset.id ? 'stop' : 'play'} size={16} color={previewingPresetId === preset.id ? '#f43f5e' : '#10b981'} />
                </TouchableOpacity>
                <Text style={styles.presetName}>{preset.name}</Text>
                <TouchableOpacity
                  style={styles.presetSetBtn}
                  onPress={() => presetKind && applyBuiltInTone(presetKind, preset)}
                  disabled={busyTone === presetKind}
                >
                  {busyTone === presetKind
                    ? <ActivityIndicator size="small" color="#0df" />
                    : <Text style={styles.presetSetText}>Set</Text>}
                </TouchableOpacity>
              </View>
            ))}
          </View>
        </View>
      </Modal>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#090d16',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 40,
  },
  avatarSection: {
    alignItems: 'center',
    marginBottom: 32,
    marginTop: 10,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#0df',
  },
  avatarFallback: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#0df',
  },
  avatarFallbackText: {
    color: '#090d16',
    fontSize: 48,
    fontWeight: '900',
  },
  cameraIconBg: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0df',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#090d16',
    shadowColor: '#0df',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  usernameText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0df',
    letterSpacing: 0.5,
  },
  profileTip: {
    fontSize: 12,
    color: '#475569',
    marginTop: 6,
  },
  formContainer: {
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 8,
    letterSpacing: 1,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(2, 6, 23, 0.5)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingHorizontal: 16,
    height: 52,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    color: '#f8fafc',
    fontSize: 15,
    height: '100%',
  },
  saveButton: {
    flexDirection: 'row',
    backgroundColor: '#0df',
    borderRadius: 12,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#0df',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  saveButtonText: {
    color: '#090d16',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  logoutButton: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderRadius: 12,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  },
  logoutButtonText: {
    color: '#ef4444',
    fontSize: 15,
    fontWeight: '700',
  },
  helpSection: {
    marginTop: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    paddingTop: 24,
  },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.02)',
  },
  helpIconBg: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 221, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  helpInfo: {
    flex: 1,
  },
  helpTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '600',
  },
  helpSubtitle: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 3,
  },
  creditText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 24,
    letterSpacing: 0.5,
  },
  personalizationSection: {
    marginTop: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    paddingTop: 24,
  },
  sectionHeaderTitle: {
    color: '#0df',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.02)',
  },
  settingInfo: {
    flex: 1,
    paddingRight: 16,
  },
  settingTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '600',
  },
  settingSubtitle: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 4,
  },
  wallpaperButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  miniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 221, 255, 0.25)',
    backgroundColor: 'rgba(0, 221, 255, 0.02)',
  },
  miniBtnText: {
    color: '#0df',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  settingRowCol: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.02)',
  },
  settingTitleCol: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
  },
  ringtoneList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  ringtoneCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    marginRight: 8,
    marginBottom: 8,
  },
  ringtoneCardActive: {
    backgroundColor: '#0df',
    borderColor: '#0df',
  },
  ringtoneText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
  },
  toneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
  },
  toneIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 221, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  toneInfo: {
    flex: 1,
    paddingRight: 8,
  },
  toneTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '600',
  },
  toneSub: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  toneIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  toneHint: {
    color: '#475569',
    fontSize: 11,
    marginTop: 12,
    lineHeight: 16,
  },
  presetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  presetCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#0f172a',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,221,255,0.25)',
    padding: 18,
  },
  presetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  presetTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  presetSub: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 12,
  },
  presetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  presetPlayBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  presetName: {
    flex: 1,
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 12,
  },
  presetSetBtn: {
    minWidth: 56,
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: 'rgba(0,221,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0,221,255,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  presetSetText: {
    color: '#0df',
    fontSize: 13,
    fontWeight: '700',
  },
  toggleSwitch: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1e293b',
    padding: 2,
    justifyContent: 'center',
  },
  toggleSwitchActive: {
    backgroundColor: '#0df',
  },
  toggleCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#94a3b8',
  },
  toggleCircleActive: {
    backgroundColor: '#090d16',
    transform: [{ translateX: 20 }],
  },
});
